#############################################################################
# Makefile for building: winmerge
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  winmerge.pro
# Template: subdirs
# Command: C:\qt\Qt5.3.1\5.3\mingw482_32\bin\qmake.exe -o Makefile winmerge.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\qt\Qt5.3.1\5.3\mingw482_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-ext \
		sub-gui


sub-ext-qmake_all:  FORCE
	@if not exist ext\ mkdir ext\ & if not exist ext\ exit 1
	cd ext\ && $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\ext\ext.pro" -o Makefile
	cd ext\ && $(MAKE) -f Makefile qmake_all
sub-ext: FORCE
	@if not exist ext\ mkdir ext\ & if not exist ext\ exit 1
	cd ext\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\ext\ext.pro" -o Makefile ) && $(MAKE) -f Makefile
sub-ext-make_first-ordered: FORCE
	@if not exist ext\ mkdir ext\ & if not exist ext\ exit 1
	cd ext\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\ext\ext.pro" -o Makefile ) && $(MAKE) -f Makefile 
sub-ext-make_first: FORCE
	@if not exist ext\ mkdir ext\ & if not exist ext\ exit 1
	cd ext\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\ext\ext.pro" -o Makefile ) && $(MAKE) -f Makefile 
sub-ext-all-ordered: FORCE
	@if not exist ext\ mkdir ext\ & if not exist ext\ exit 1
	cd ext\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\ext\ext.pro" -o Makefile ) && $(MAKE) -f Makefile all
sub-ext-all: FORCE
	@if not exist ext\ mkdir ext\ & if not exist ext\ exit 1
	cd ext\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\ext\ext.pro" -o Makefile ) && $(MAKE) -f Makefile all
sub-ext-clean-ordered: FORCE
	@if not exist ext\ mkdir ext\ & if not exist ext\ exit 1
	cd ext\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\ext\ext.pro" -o Makefile ) && $(MAKE) -f Makefile clean
sub-ext-clean: FORCE
	@if not exist ext\ mkdir ext\ & if not exist ext\ exit 1
	cd ext\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\ext\ext.pro" -o Makefile ) && $(MAKE) -f Makefile clean
sub-ext-distclean-ordered: FORCE
	@if not exist ext\ mkdir ext\ & if not exist ext\ exit 1
	cd ext\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\ext\ext.pro" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ext-distclean: FORCE
	@if not exist ext\ mkdir ext\ & if not exist ext\ exit 1
	cd ext\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\ext\ext.pro" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ext-install_subtargets-ordered: FORCE
	@if not exist ext\ mkdir ext\ & if not exist ext\ exit 1
	cd ext\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\ext\ext.pro" -o Makefile ) && $(MAKE) -f Makefile install
sub-ext-install_subtargets: FORCE
	@if not exist ext\ mkdir ext\ & if not exist ext\ exit 1
	cd ext\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\ext\ext.pro" -o Makefile ) && $(MAKE) -f Makefile install
sub-ext-uninstall_subtargets-ordered: FORCE
	@if not exist ext\ mkdir ext\ & if not exist ext\ exit 1
	cd ext\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\ext\ext.pro" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-ext-uninstall_subtargets: FORCE
	@if not exist ext\ mkdir ext\ & if not exist ext\ exit 1
	cd ext\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\ext\ext.pro" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-gui-qmake_all: sub-ext-qmake_all FORCE
	@if not exist gui\ mkdir gui\ & if not exist gui\ exit 1
	cd gui\ && $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\gui\gui.pro" -o Makefile
	cd gui\ && $(MAKE) -f Makefile qmake_all
sub-gui: FORCE
	@if not exist gui\ mkdir gui\ & if not exist gui\ exit 1
	cd gui\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\gui\gui.pro" -o Makefile ) && $(MAKE) -f Makefile
sub-gui-make_first-ordered: sub-ext-make_first-ordered  FORCE
	@if not exist gui\ mkdir gui\ & if not exist gui\ exit 1
	cd gui\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\gui\gui.pro" -o Makefile ) && $(MAKE) -f Makefile 
sub-gui-make_first: FORCE
	@if not exist gui\ mkdir gui\ & if not exist gui\ exit 1
	cd gui\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\gui\gui.pro" -o Makefile ) && $(MAKE) -f Makefile 
sub-gui-all-ordered: sub-ext-all-ordered  FORCE
	@if not exist gui\ mkdir gui\ & if not exist gui\ exit 1
	cd gui\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\gui\gui.pro" -o Makefile ) && $(MAKE) -f Makefile all
sub-gui-all: FORCE
	@if not exist gui\ mkdir gui\ & if not exist gui\ exit 1
	cd gui\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\gui\gui.pro" -o Makefile ) && $(MAKE) -f Makefile all
sub-gui-clean-ordered: sub-ext-clean-ordered  FORCE
	@if not exist gui\ mkdir gui\ & if not exist gui\ exit 1
	cd gui\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\gui\gui.pro" -o Makefile ) && $(MAKE) -f Makefile clean
sub-gui-clean: FORCE
	@if not exist gui\ mkdir gui\ & if not exist gui\ exit 1
	cd gui\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\gui\gui.pro" -o Makefile ) && $(MAKE) -f Makefile clean
sub-gui-distclean-ordered: sub-ext-distclean-ordered  FORCE
	@if not exist gui\ mkdir gui\ & if not exist gui\ exit 1
	cd gui\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\gui\gui.pro" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-gui-distclean: FORCE
	@if not exist gui\ mkdir gui\ & if not exist gui\ exit 1
	cd gui\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\gui\gui.pro" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-gui-install_subtargets-ordered: sub-ext-install_subtargets-ordered  FORCE
	@if not exist gui\ mkdir gui\ & if not exist gui\ exit 1
	cd gui\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\gui\gui.pro" -o Makefile ) && $(MAKE) -f Makefile install
sub-gui-install_subtargets: FORCE
	@if not exist gui\ mkdir gui\ & if not exist gui\ exit 1
	cd gui\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\gui\gui.pro" -o Makefile ) && $(MAKE) -f Makefile install
sub-gui-uninstall_subtargets-ordered: sub-ext-uninstall_subtargets-ordered  FORCE
	@if not exist gui\ mkdir gui\ & if not exist gui\ exit 1
	cd gui\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\gui\gui.pro" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-gui-uninstall_subtargets: FORCE
	@if not exist gui\ mkdir gui\ & if not exist gui\ exit 1
	cd gui\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\gui\gui.pro" -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: winmerge.pro C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/spec_pre.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/qdevice.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/device_config.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/common/shell-win32.conf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/qconfig.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_clucene_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_core.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_core_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_designer.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_designer_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_gui.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_gui_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_help.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_help_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_network.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_network_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_qml.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_qml_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_quick.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_quick_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_script.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_script_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_sql.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_sql_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_svg.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_svg_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_xml.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_xml_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/qt_functions.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/qt_config.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/win32/qt_config.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/spec_post.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/exclusive_builds.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/default_pre.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/win32/default_pre.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/resolve_config.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/exclusive_builds_post.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/default_post.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/win32/rtti.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/precompile_header.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/warn_on.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/win32/windows.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/testcase_targets.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/exceptions.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/yacc.prf \
		C:/qt/Qt5.3.1/5.3/mingw482_32/mkspecs/features/lex.prf \
		winmerge.pro
	$(QMAKE) -o Makefile winmerge.pro
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\spec_pre.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\qdevice.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\device_config.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\common\shell-win32.conf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\qconfig.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_axbase.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_axbase_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_axcontainer.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_axserver.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_axserver_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_bluetooth.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_clucene_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_concurrent.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_core.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_core_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_declarative.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_declarative_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_designer.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_designer_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_enginio.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_enginio_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_gui.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_gui_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_help.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_help_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_multimedia.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_network.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_network_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_nfc.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_nfc_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_opengl.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_opengl_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_openglextensions.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_positioning.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_positioning_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_printsupport.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_qml.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_qml_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_qmltest.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_quick.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_quick_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_script.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_script_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_scripttools.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_sensors.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_sensors_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_serialport.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_serialport_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_sql.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_sql_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_svg.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_svg_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_testlib.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_testlib_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_uitools.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_uitools_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_webkit.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_webkit_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_webkitwidgets.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_websockets.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_websockets_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_widgets.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_widgets_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_winextras.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_winextras_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_xml.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_xml_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\qt_functions.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\qt_config.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\win32\qt_config.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\win32-g++\qmake.conf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\spec_post.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\exclusive_builds.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\default_pre.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\win32\default_pre.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\resolve_config.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\exclusive_builds_post.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\default_post.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\win32\rtti.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\precompile_header.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\warn_on.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\win32\windows.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\testcase_targets.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\exceptions.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\yacc.prf:
C:\qt\Qt5.3.1\5.3\mingw482_32\mkspecs\features\lex.prf:
winmerge.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile winmerge.pro

qmake_all: sub-ext-qmake_all sub-gui-qmake_all FORCE

make_first: sub-ext-make_first-ordered sub-gui-make_first-ordered FORCE
all: sub-ext-all-ordered sub-gui-all-ordered FORCE
clean: sub-ext-clean-ordered sub-gui-clean-ordered FORCE
distclean: sub-ext-distclean-ordered sub-gui-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-ext-install_subtargets-ordered sub-gui-install_subtargets-ordered FORCE
uninstall_subtargets: sub-ext-uninstall_subtargets-ordered sub-gui-uninstall_subtargets-ordered FORCE

sub-ext-debug_ordered:
	@if not exist ext\ mkdir ext\ & if not exist ext\ exit 1
	cd ext\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\ext\ext.pro" -o Makefile ) && $(MAKE) -f Makefile debug
sub-gui-debug_ordered: sub-ext-debug_ordered 
	@if not exist gui\ mkdir gui\ & if not exist gui\ exit 1
	cd gui\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\gui\gui.pro" -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-ext-debug_ordered sub-gui-debug_ordered

sub-ext-release_ordered:
	@if not exist ext\ mkdir ext\ & if not exist ext\ exit 1
	cd ext\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\ext\ext.pro" -o Makefile ) && $(MAKE) -f Makefile release
sub-gui-release_ordered: sub-ext-release_ordered 
	@if not exist gui\ mkdir gui\ & if not exist gui\ exit 1
	cd gui\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\gui\gui.pro" -o Makefile ) && $(MAKE) -f Makefile release
release: sub-ext-release_ordered sub-gui-release_ordered

sub-ext-check_ordered:
	@if not exist ext\ mkdir ext\ & if not exist ext\ exit 1
	cd ext\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\ext\ext.pro" -o Makefile ) && $(MAKE) -f Makefile check
sub-gui-check_ordered: sub-ext-check_ordered 
	@if not exist gui\ mkdir gui\ & if not exist gui\ exit 1
	cd gui\ && ( if not exist Makefile $(QMAKE) "C:\Games\Dwarf Fortress\dev\winmerge\v3 qt\grimmdp-winmerge-1bd708f4cf72\grimmdp-winmerge-1bd708f4cf72\gui\gui.pro" -o Makefile ) && $(MAKE) -f Makefile check
check: sub-ext-check_ordered sub-gui-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

